"""Three business questions, answered with EDA — and only vizz charts.

Run from phase-02-eda/:   python src/analysis.py

Prints a report (with an explicit Business answer per question) and writes
SVG charts to charts/. Data wrangling is pandas; every pixel on screen is
generated by src/vizz — pure Python, no charting libraries.

STRUCTURE: each qN function = one business question, and follows the
same shape:
  1. WRANGLE  - pandas groupby/agg until a small table holds the answer
  2. VISUALIZE- hand that table to a vizz Figure and save the SVG
  3. ANSWER   - print the finding in business language, not data language
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

# make src/ importable when run as a script, and force utf-8 output so
# the unicode block chars in vizz.ascii survive Windows' cp1252 console
sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import clean as cl  # noqa: E402  (import after sys.path tweak - deliberate)
from vizz import Figure, ascii as va  # noqa: E402

CHARTS = Path(__file__).resolve().parent.parent / "charts"
DOW = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]


def q1_customer_concentration(sales: pd.DataFrame) -> None:
    """Q1: How concentrated is revenue across customers? (Pareto analysis)

    WRANGLE: revenue per customer (groupby-sum), sorted biggest first.
    The Pareto question is then two cumulative stats:
      - what share of revenue does the top 10% of customers hold?
      - how many customers does it take to reach 50% of revenue?
    VISUALIZE: top-10 customers as horizontal bars (long labels).
    """
    # only rows WITH a CustomerID can count toward customer analysis
    cust = (
        sales[sales["HasCustomer"]]
        .groupby("CustomerID")["Revenue"]
        .sum()
        .sort_values(ascending=False)
    )
    total = cust.sum()
    # top 10% of customers, but at least 1 (int() would give 0 on tiny data)
    share_top10pct = cust.head(max(1, int(len(cust) * 0.10))).sum() / total
    # cumulative share: after k customers, how much of the total is covered?
    cum_share = cust.cumsum() / total
    first_at_50 = int((cum_share < 0.50).sum()) + 1   # first customer past 50%

    top = cust.head(10)
    fig = Figure(900, 520, "Q1 - Top 10 customers by revenue (Pareto)")
    fig.barh(
        [f"Cust {int(c)}" for c in top.index],   # CustomerID is a float here
        top.values,
        prefix="\u00a3",
    )
    fig.save(CHARTS / "pareto_customers.svg")

    print("== Q1. Revenue concentration ==")
    print(f"  customers analysed        : {len(cust):,}")
    print(f"  top 10% of customers      : {share_top10pct:.1%} of revenue")
    print(f"  customers to reach 50%    : {first_at_50} of {len(cust):,}"
          f"  ({first_at_50 / len(cust):.1%})")
    print(f"  ANSWER: revenue is heavily concentrated - the top ~10% of "
          f"customers drive {share_top10pct:.0%} of revenue. Retention of "
          f"that tier matters more than broad acquisition.")
    print()


def q2_seasonality(sales: pd.DataFrame) -> None:
    """Q2: When do people buy? Monthly trend, weekday and hour patterns.

    WRANGLE: three groupbys off InvoiceDate's datetime parts —
    .dt.to_period('M') for months, .dt.dayofweek (Mon=0), .dt.hour.
    VISUALIZE: a line for the trend, bars for the two cycles.
    """
    # .dt.to_period('M') buckets timestamps by calendar month
    monthly = sales.groupby(sales["InvoiceDate"].dt.to_period("M"))["Revenue"].sum()
    labels = [str(p) for p in monthly.index]
    # dayofweek: Monday=0 .. Sunday=6 (mapped to names via DOW list)
    by_dow = sales.groupby(sales["InvoiceDate"].dt.dayofweek)["Revenue"].sum()
    by_hour = sales.groupby(sales["InvoiceDate"].dt.hour)["Revenue"].sum()

    fig = Figure(900, 480, "Q2 - Monthly revenue (note: Dec 2011 is a partial month)")
    fig.line(labels, monthly.values, prefix="\u00a3")
    fig.save(CHARTS / "monthly_revenue.svg")

    fig = Figure(900, 440, "Q2 - Revenue by day of week")
    fig.bar([DOW[i] for i in by_dow.index], by_dow.values, prefix="\u00a3",
            value_labels=True)
    fig.save(CHARTS / "revenue_by_dow.svg")

    # top 3 hours by revenue, for the printed answer
    peak_hours = by_hour.sort_values(ascending=False).head(3)
    fig = Figure(900, 440, "Q2 - Revenue by hour of day")
    fig.bar([f"{h:02d}" for h in by_hour.index], by_hour.values, prefix="\u00a3",
            label_every=2)
    fig.save(CHARTS / "revenue_by_hour.svg")

    best_dow = DOW[int(by_dow.idxmax())]
    print("== Q2. Seasonality ==")
    print(f"  monthly trend             : {va.sparkline(monthly.values)}")
    print(f"  peak month                : {labels[int(monthly.values.argmax())]}"
          f"  (partial: the data ends 2011-12-09)")
    print(f"  best weekday              : {best_dow}"
          f"  ({by_dow.max() / by_dow.sum():.1%} of weekly revenue)")
    print(f"  peak hours                : "
          + ", ".join(f"{h:02d}:00" for h in peak_hours.index))
    print(f"  ANSWER: demand builds to a November peak (holiday gifting) and "
          f"concentrates on weekday working hours - staff and stock before "
          f"Nov, not during it.")
    print()


def q3_returns_and_cancellations(df: pd.DataFrame, sales: pd.DataFrame) -> None:
    """Q3: What comes back — and is it money or stock? Two different phenomena.

    EDA discovery: the negative-quantity rows on normal invoices all have
    UnitPrice = 0 — they are damaged-stock write-offs, not refunds. The
    real money refunds live in the C-prefixed cancellation invoices.
    Most analyses of this dataset lump the two together and get it wrong.

    WRANGLE: the clean() flags (IsCancelled / IsReturn) split the two;
    the numbers fall out of two groupbys.
    """
    cancellations = df[df["IsCancelled"]]
    writeoffs = df[df["IsReturn"]]
    gross = sales["Revenue"].sum()
    refund_value = cancellations["Revenue"].abs().sum()

    # units written off per product (Quantity is negative -> abs it)
    by_product = (
        writeoffs.groupby("StockCode")["Quantity"]
        .apply(lambda q: q.abs().sum())
        .sort_values(ascending=False)
        .head(10)
    )
    # one description per product: first non-null, else '?'
    desc = (
        writeoffs.groupby("StockCode")["Description"]
        .agg(lambda d: d.dropna().iloc[0] if d.dropna().size else "?")
    )
    labels = [f"{code} - {str(desc.get(code, '?'))[:30]}" for code in by_product.index]

    fig = Figure(1000, 520, "Q3 - Top 10 written-off products (units disposed)")
    fig.barh(labels, by_product.values)
    fig.save(CHARTS / "top_written_off_products.svg")

    print("== Q3. Returns & cancellations ==")
    print(f"  cancellations (C invoices): {len(cancellations):,} rows")
    print(f"  refund value              : \u00a3{refund_value:,.0f}"
          f"  ({refund_value / gross:.1%} of gross sales)")
    print(f"  write-offs (Quantity<0, price 0): {len(writeoffs):,} rows - no revenue impact")
    print(f"  most written-off product  : {labels[0]}")
    print(f"  ANSWER: 'returns' here are two different problems. Cancellations")
    print(f"  refund \u00a3{refund_value / 1000:,.0f}k ({refund_value / gross:.0%} of gross) - a commercial")
    print(f"  question. Write-offs are damaged stock at zero price - an")
    print(f"  operations question. Fixing them needs different owners.")
    print()


def bonus_basket(sales: pd.DataFrame) -> None:
    """Bonus: what does one order look like? (invoice-level distribution)

    WRANGLE: collapse line items to one row per invoice (groupby-sum),
    then look at the DISTRIBUTION of order values. Mean vs median is
    the fastest skew check there is: mean >> median = a long right tail.
    The histogram clips at the 99th percentile — one giant order would
    otherwise squash every other bin into invisibility.
    """
    baskets = sales.groupby("InvoiceNo")["Revenue"].sum()
    clip = baskets.clip(upper=baskets.quantile(0.99))

    fig = Figure(900, 460, "Bonus - Order value distribution (clipped at p99)")
    fig.histogram(clip, bins=24)
    fig.save(CHARTS / "order_value_histogram.svg")

    print("== Bonus. Basket shape ==")
    print(f"  orders                    : {len(baskets):,}")
    print(f"  average order value       : \u00a3{baskets.mean():,.2f}")
    print(f"  median order value        : \u00a3{baskets.median():,.2f}")
    print(f"  mean >> median => a few huge wholesale orders pull the average up")
    print(clip.describe().to_string(float_format=lambda v: f"{v:,.1f}"))
    print()


def main() -> None:
    """Run the whole report: clean once, answer every question, save charts."""
    df = cl.clean(cl.load())
    sales = cl.sales(df)

    print("=" * 64)
    print(" PHASE 2 - EDA on Online Retail (541,909 raw rows)")
    print("=" * 64)
    print(cl.summary(df))
    print()

    q1_customer_concentration(sales)
    q2_seasonality(sales)
    q3_returns_and_cancellations(df, sales)
    bonus_basket(sales)

    print(f"charts written to: {CHARTS}")


if __name__ == "__main__":
    main()